/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>


int main(void)
{

	uint32_t volatile *RCC_AHB1ENR = (uint32_t *) 0x40023830;
 	uint32_t volatile *GPIOA_MODER = (uint32_t *) 0x40020000;
 	uint32_t volatile *GPIOA_IDR   = (uint32_t *) 0x40020010;

	uint32_t volatile *pClockControlReg = (uint32_t *) 0x40023830;
	uint32_t volatile *pPortDModeReg = (uint32_t *) 0x40020C00;
	uint32_t volatile *pPortDOutReg = (uint32_t *) 0x40020C14;




	// Enable RCC AHB1 Clock for Port A
	*RCC_AHB1ENR |= (1<<0);
	// Set PA0 to input
	*GPIOA_MODER  &= ~(3 << 0);

	// Enable RCC for Port D
	*pClockControlReg |= (1 << 3);

	// Clear Port D Pin 12
	*pPortDModeReg = *pPortDModeReg & ~(3 << 24);
	// Set Port D Pin 12 as output
	*pPortDModeReg = *pPortDModeReg | (1<< 24);





	while (1) {
		if (*GPIOA_IDR & (1 << 0)) {
			// bit read is 1
			*pPortDOutReg |= (1 << 12);


		} else {
			// bit read is 0
			*pPortDOutReg &= ~(1 << 12);

		}
	}



    /* Loop forever */
	for(;;);
}
