/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>


int main(void)
{
	uint32_t *pClockControlReg = (uint32_t *) 0x40023830;
	uint32_t *pPortDModeReg = (uint32_t *) 0x40020C00;
	uint32_t *pPortDOutReg = (uint32_t *) 0x40020C14;


// 1. Enable the clock for GPIO D in AHB1ENR
	//*pClockControlReg |= x08; //0x00000008
	*pClockControlReg |= (1 << 3);

// 2. configure the mode of the IO pin as output
	// a. clear 24th and 25th bit position
	// *pPortDModeReg = *pPortDModeReg & 0xFCFFFFFF;
	*pPortDModeReg = *pPortDModeReg & ~(3 << 24);

	// set 24 bit position to one
	//*pPortDModeReg = *pPortDModeReg | 0x01000000;
	*pPortDModeReg = *pPortDModeReg | (1<< 24);

// 3. SET 12th bit of output data register as high to turn on LED
	//*pPortDOutReg |= 0x1000;

	*pPortDOutReg|= (1 << 12);

    /* Loop forever */
	for(;;);
}
